on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: lucasrod96/update-dockerhub-description
          readme-filepath: ./README.md
